### ISSUE TITLE
[Enhancement] Request function 'pause'

### ISSUE THREAD

**Issue by b3lon9** [lichess-org/flutter-sound-effect#1]
Hi @lichess-org!

I needed a simple function to put sound effects, I think your package would be such a package.
But I think it would be better if you added `pause` function.

Thanks!

**Comment by veloce** [comment]
Hi!

We created this package for the lichess mobile app, and we don't need the `pause` function. So I won't be implementing it.

I'd recommend you to use [soundpool](https://pub.dev/packages/soundpool) package instead, which does support pause.

**Comment by b3lon9** [comment]
> Hi!
> 
> We created this package for the lichess mobile app, and we don't need the `pause` function. So I won't be implementing it.
> 
> I'd recommend you to use [soundpool](https://pub.dev/packages/soundpool) package instead, which does support pause.

Thanks for the tip!
